const adminApp = document.querySelector('#admin-app');
const storageKey = 'buguCupRegistrations';

function login() {
  adminApp.innerHTML = `<section class="admin-login"><a class="registration-brand" href="index.html">BUGU <span>CUP</span><small>ADMIN</small></a><div><span class="eyebrow">Accesso riservato</span><h1>Area<br>amministratore.</h1><p>Inserisci la password per vedere le iscrizioni.</p><input class="admin-password" id="password" type="password" inputmode="numeric" placeholder="Password"><button class="next" onclick="unlock()">Accedi →</button><small id="login-error"></small></div></section>`;
}
function unlock() { if (document.querySelector('#password').value !== '1948') { document.querySelector('#login-error').textContent = 'Password non corretta.'; return; } sessionStorage.setItem('buguAdmin', 'true'); dashboard(); }
function readEntries() { return JSON.parse(localStorage.getItem(storageKey) || '[]'); }
function writeEntries(entries) { localStorage.setItem(storageKey, JSON.stringify(entries)); }
function dashboard() {
  const entries = readEntries(); const peopleCount = entries.reduce((total, entry) => total + entry.people.length, 0); const pingCount = entries.reduce((total, entry) => total + entry.tournament.length, 0);
  adminApp.innerHTML = `<div class="admin-workspace"><header class="admin-header"><a class="registration-brand" href="index.html">BUGU <span>CUP</span><small>ADMIN / XI</small></a><div><button class="print-button" onclick="window.print()">Salva in PDF</button><button class="logout-button" onclick="logout()">Esci</button></div></header><section class="admin-summary"><div><span>Iscrizioni</span><b>${entries.length}</b></div><div><span>Partecipanti</span><b>${peopleCount}</b></div><div><span>Ping Pong</span><b>${pingCount}</b></div></section><section class="admin-table-wrap"><div class="admin-table-title"><div><span class="eyebrow">Dati raccolti</span><h1>Iscrizioni Bugu Cup</h1></div><p>${entries.length ? 'Puoi rimuovere un singolo nome o un’intera iscrizione.' : 'Non ci sono ancora iscrizioni inviate.'}</p></div>${entries.length ? table(entries) : `<div class="empty-admin">Quando un questionario viene inviato, comparirà qui.</div>`}</section></div>`;
}
function table(entries) { return `<div class="admin-table">${entries.map(entry => `<article class="entry"><header><div><b>${escapeHtml(entry.contact)}</b><small>${new Date(entry.createdAt).toLocaleString('it-IT')}</small></div><button class="delete-entry" onclick="deleteEntry('${entry.id}')">Elimina iscrizione</button></header><div class="entry-grid"><div><span>Partecipanti (${entry.people.length})</span><div class="name-list">${entry.people.map(person => `<button class="name-chip" title="Elimina ${escapeHtml(person.name)}" onclick="deletePerson('${entry.id}','${person.id}')">${escapeHtml(person.name)} <b>×</b></button>`).join('')}</div></div><div><span>Cibo</span><b>${escapeHtml(entry.food)}</b><p>${escapeHtml(entry.foodDetail)}</p></div><div><span>Ping Pong</span><p>${entry.noTournament ? 'Nessuno' : entry.tournament.map(player => `${escapeHtml(player.name)} (${player.type})`).join(', ')}</p></div><div><span>Swap Party</span><b>${escapeHtml(entry.swap)}</b></div></div></article>`).join('')}</div>`; }
function deletePerson(entryId, personId) { const entries = readEntries(); const entry = entries.find(item => item.id === entryId); if (!entry) return; entry.people = entry.people.filter(person => person.id !== personId); entry.tournament = entry.tournament.filter(player => player.personId !== personId); if (!entry.people.length) { writeEntries(entries.filter(item => item.id !== entryId)); } else { writeEntries(entries); } dashboard(); }
function deleteEntry(entryId) { if (!confirm('Eliminare questa iscrizione?')) return; writeEntries(readEntries().filter(entry => entry.id !== entryId)); dashboard(); }
function logout() { sessionStorage.removeItem('buguAdmin'); login(); }
function escapeHtml(text) { return String(text || '').replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' })[char]); }
sessionStorage.getItem('buguAdmin') === 'true' ? dashboard() : login();
