const app = document.querySelector('#app');

app.innerHTML = `
  <div class="shell" id="home">
    <section class="hero">
      <header class="topbar"><div class="brand">BUGU <span>CUP</span></div><nav class="nav"><a href="#storia">La storia</a><a href="#programma">Programma</a><a href="#gallery">Ricordi</a></nav><div class="edition">XI edizione / 2026</div></header>
      <div class="hero-content"><div class="kicker"><i class="dot"></i> Buguggiate, VA - la partita e iniziata</div><h1>Bugu<br>cup <em>XI</em></h1><p class="sub">Una rivalita lunga dieci edizioni. Cento amici, una casa di campagna e un risultato ancora da decidere.</p><div class="actions"><a class="primary link-button" href="registration.html">Partecipa alla leggenda</a><button class="text-button" onclick="document.querySelector('#storia').scrollIntoView()">Scopri la storia ↓</button></div><div class="score"><div class="score-item"><span class="score-label">Bianchi</span><span class="score-value">5</span></div><div class="score-mid">BILANCIO<br>STORICO</div><div class="score-item" style="padding-left:18px"><span class="score-label">Verdi</span><span class="score-value">5</span></div></div></div>
      <aside class="hero-meta"><span>SABATO 12 SETTEMBRE</span><span>VIA DEL CAMPO, BUGUGGIATE</span></aside>
    </section>
    <section class="section story" id="storia"><div class="story-grid"><div><span class="eyebrow" style="color:#d4502d">Dal 2016, molto seriamente</span><h2 class="section-title">Non e una semplice festa tra amici.</h2><p class="story-copy">E la Bugu Cup: una giornata di calcio, grigliata, ping pong e racconti che con gli anni diventano sempre piu epici. Trattiamo ogni dettaglio come una finale mondiale. Anche il dolce.</p></div><blockquote class="quote">"L'XI edizione rompe l'equilibrio. O almeno ci prova."</blockquote></div></section>
    <section class="section" id="programma"><span class="eyebrow">Il calendario ufficiale</span><h2 class="section-title">Un giorno. Mille momenti memorabili.</h2><div class="timeline"><div class="time"><b>11:00</b><span>Arrivi &<br>abbracci</span></div><div class="time"><b>12:30</b><span>Pranzo da<br>campioni</span></div><div class="time"><b>14:30</b><span>Ping Pong<br>Open</span></div><div class="time"><b>16:00</b><span>Swap<br>Party</span></div><div class="time"><b>17:30</b><span>La<br>partita</span></div><div class="time"><b>19:30 →</b><span>Cena &<br>festa</span></div></div></section>
    <section class="section gallery" id="gallery"><span class="eyebrow">Archivio emozioni</span><h2 class="section-title">Dieci anni in una foto.</h2><div class="gallery-grid"><figure class="card-img"><img src="assets/water-01.jpg" alt="Festa Bugu Cup"><figcaption class="caption">L'acqua e la festa</figcaption></figure><figure class="card-img"><img src="assets/water-03.jpg" alt="Festa serale"><figcaption class="caption">Dopo il fischio</figcaption></figure><figure class="card-img"><img src="assets/water-04.jpg" alt="Giochi"><figcaption class="caption">Nessuna tregua</figcaption></figure><figure class="card-img"><img src="assets/water-05.jpg" alt="Festa"><figcaption class="caption">La piazza</figcaption></figure><figure class="card-img"><img src="assets/water-06.jpg" alt="Amici"><figcaption class="caption">La squadra</figcaption></figure></div></section>
    <section class="cta-strip"><div><h2>La squadra aspetta solo voi.</h2><p>Iscriviti in meno di due minuti.</p></div><a class="primary link-button" href="registration.html">Partecipa ora</a></section>
    <footer class="site-footer"><span>BUGU CUP XI / BUGUGGIATE</span><a href="admin.html">Admin</a></footer>
  </div>`;
